/**
 * Centralized API request functions.
 * It's good practice to use environment variables for the base URL.
 * Create a .env.local file in your root directory and add:
 * NEXT_PUBLIC_API_URL=http://localhost:5000/api/v1
 */
const API_BASE_URL =
  process.env.NEXT_PUBLIC_API_URL || "http://localhost:8080/api/v1";

/**
 * A helper function to handle API responses and errors.
 * @param response The Response object from a fetch call.
 */
async function handleResponse(response: Response) {
  // If the response is not OK (status code 200-299), parse the error and throw it.
  if (!response.ok) {
    const errorData = await response
      .json()
      .catch(() => ({ message: "An unknown error occurred" }));
    throw new Error(
      errorData.message || `HTTP error! status: ${response.status}`
    );
  }
  // Otherwise, parse and return the JSON data.
  return response.json();
}

/**
 * A generic and reusable function for making API requests.
 * @param endpoint The API endpoint to call (e.g., '/users/login-rider').
 * @param options The RequestInit options for the fetch call.
 */
async function apiRequest(endpoint: string, options: RequestInit = {}) {
  const url = `${API_BASE_URL}${endpoint}`;
  const defaultHeaders = {
    "Content-Type": "application/json",
  };

  const config: RequestInit = {
    ...options,
    headers: {
      ...defaultHeaders,
      ...options.headers,
    },
  };

  const response = await fetch(url, config);
  return handleResponse(response);
}

// --- Authentication API Calls ---

/**
 * Requests an OTP for a given phone number.
 * Corresponds to: POST /users/request-otp
 */
export const requestOTP = (phoneNumber: string) => {
  return apiRequest("/users/request-otp", {
    method: "POST",
    body: JSON.stringify({ phoneNumber }),
  });
};

/**
 * Verifies an OTP for a given phone number.
 * Corresponds to: POST /users/verify-otp
 */
export const verifyOTP = (phoneNumber: string, otp: string) => {
  return apiRequest("/users/verify-otp", {
    method: "POST",
    body: JSON.stringify({ phoneNumber, otp }),
  });
};

/**
 * Logs in a rider with email and password.
 * Corresponds to: POST /users/login-rider
 */
export const loginRider = (credentials: {
  email: string;
  password: string;
}) => {
  return apiRequest("/users/login-rider", {
    method: "POST",
    body: JSON.stringify(credentials),
  });
};

/**
 * Registers a new rider.
 * Corresponds to: POST /users/register-rider
 * Note: You should create a specific TypeScript type for 'riderData'.
 */
export const registerRider = (riderData: any) => {
  return apiRequest("/users/register-rider", {
    method: "POST",
    body: JSON.stringify(riderData),
  });
};

/**
 * Fetches the current user's profile information.
 * Corresponds to: GET /users/me
 */
export const getUserProfile = (token: string) => {
  return apiRequest("/users/me", {
    method: "GET",
    headers: {
      Authorization: `Bearer ${token}`,
    },
  });
};

// You can add more API functions here for drivers, trips, etc. as you build them.
export interface UpdateUserProfilePayload {
  fullName: string;
  email: string;
  phone: string;
  gender: string;
  dateOfBirth?: string;
}

export interface User {
  _id: string;
  phone: string;
  email: string;
  fullName: string;
  gender: string;
  dateOfBirth: string;
  role: "rider" | "driver";
  isVerified: boolean;
  emergencyContact: {
    name: string;
    relationship: string;
    phone: string;
  };
}

// const API_BASE_URL =
//   process.env.NEXT_PUBLIC_API_URL || "http://localhost:8080/api/v1";

export const updateUserProfile = async (
  payload: UpdateUserProfilePayload,
  token: string
): Promise<User> => {
  const response = await fetch(`${API_BASE_URL}/users/me`, {
    method: "PATCH",
    headers: {
      "Content-Type": "application/json",
      Authorization: `Bearer ${token}`,
    },
    body: JSON.stringify(payload),
  });

  if (!response.ok) {
    const errData = await response
      .json()
      .catch(() => ({ message: "An unknown error occurred" }));
    throw new Error(
      errData.message || `Request failed with status ${response.status}`
    );
  }

  const responseData = await response.json();
  return responseData.data.user;
<<<<<<< Updated upstream
=======
};

// ─────────────────────────────────────────────────────────────
//  TRIP TYPES
// ─────────────────────────────────────────────────────────────

export type TripStatus = "scheduled" | "active" | "completed" | "cancelled";
export type LuggagePolicy = "none" | "light" | "medium" | "heavy";

export interface TripLocation {
  address: string;
  city: string;
  state: string;
  coordinates: [number, number]; // [lng, lat] — auto-generated by backend
  _id?: string;
}

// Stop shape for CREATE payload — coordinates optional, backend fills them
export interface TripStopInput {
  address: string;
  city: string;
  state: string;
  coordinates?: [number, number];
}

export interface TripPreferences {
  smokingAllowed: boolean;
  petsAllowed: boolean;
  luggagePolicy: LuggagePolicy;
  instantBooking: boolean;
}

// Vehicle shape returned inside trip from GET /trips/my-trips (populated)
export interface TripVehicle {
  make: string;
  model: string;
  year: string;
  color: string;
  plateNumber: string;
}

// Full Trip shape — matches GET /trips/my-trips response
export interface Trip {
  _id: string;
  id: string;
  driver: string;
  vehicle: TripVehicle | string; // populated object from /my-trips, string id from POST /trips
  origin: TripLocation;
  destination: TripLocation;
  stops: TripLocation[];
  departureTime: string;
  pricePerSeat: number;
  totalSeats: number;
  availableSeats: number;
  status: TripStatus;
  description?: string;
  preferences: TripPreferences;
  bookings: string[];
  createdAt: string;
  updatedAt: string;
}

// Create Trip Payload — matches POST /trips body
// originAddress and destinationAddress are flat strings.
// Backend geocodes them into full TripLocation objects with coordinates.
export interface CreateTripPayload {
  originAddress: string; // e.g. "Ikeja City Mall, Lagos"
  destinationAddress: string; // e.g. "Jabi Lake Mall, Abuja"
  departureTime: string; // ISO date string
  pricePerSeat: number;
  totalSeats: number;
  stops?: TripStopInput[]; // optional — coordinates auto-generated
  preferences: TripPreferences;
  description?: string;
}

// ─────────────────────────────────────────────────────────────
//  TRIP ENDPOINTS
// ─────────────────────────────────────────────────────────────

/**
 * Creates a new trip.
 * Corresponds to: POST /trips
 */
export const createTrip = async (
  payload: CreateTripPayload,
  token: string
): Promise<Trip> => {
  const response = await fetch(`${API_BASE_URL}/trips`, {
    method: "POST",
    headers: {
      "Content-Type": "application/json",
      Authorization: `Bearer ${token}`,
    },
    body: JSON.stringify(payload),
  });

  if (!response.ok) {
    const errData = await response
      .json()
      .catch(() => ({ message: "An unknown error occurred" }));
    throw new Error(
      errData.message || `Request failed with status ${response.status}`
    );
  }

  const data = await response.json();
  return data.data.trip;
};

/**
 * Fetches all trips for the logged-in driver.
 * Corresponds to: GET /trips/my-trips
 */
export const getMyTrips = async (
  token: string
): Promise<{ status: string; results: number; data: { trips: Trip[] } }> => {
  const response = await fetch(`${API_BASE_URL}/trips/my-trips`, {
    method: "GET",
    headers: {
      "Content-Type": "application/json",
      Authorization: `Bearer ${token}`,
    },
  });

  if (!response.ok) {
    const errData = await response
      .json()
      .catch(() => ({ message: "An unknown error occurred" }));
    throw new Error(
      errData.message || `Request failed with status ${response.status}`
    );
  }

  return response.json();
};

/**
 * Fetches a single trip by ID.
 * Corresponds to: GET /trips/:id
 */
export const getTripById = (tripId: string, token: string) =>
  apiRequest(`/trips/${tripId}`, {
    method: "GET",
    headers: { Authorization: `Bearer ${token}` },
  });

/**
 * Cancels a trip.
 * Corresponds to: PATCH /trips/:id/cancel
 */
export const cancelTrip = (tripId: string, token: string) =>
  apiRequest(`/trips/${tripId}/cancel`, {
    method: "PATCH",
    headers: { Authorization: `Bearer ${token}` },
  });



  // ─────────────────────────────────────────────────────────────
//  PUBLIC TRIP SEARCH (for riders)
// ─────────────────────────────────────────────────────────────

export interface TripSearchParams {
  origin?: string;        // city name filter
  destination?: string;   // city name filter
  date?: string;          // ISO date string
  seats?: number;         // minimum available seats needed
}

export const getAvailableTrips = async (
  token: string
): Promise<{ status: string; results: number; data: { trips: Trip[] } }> => {
  const response = await fetch(`${API_BASE_URL}/trips`, {
    method: "GET",
    headers: {
      "Content-Type": "application/json",
      Authorization: `Bearer ${token}`,
    },
  });

  if (!response.ok) {
    const errData = await response
      .json()
      .catch(() => ({ message: "An unknown error occurred" }));
    throw new Error(
      errData.message || `Request failed with status ${response.status}`
    );
  }

  return response.json();
};



// ─────────────────────────────────────────────────────────────
//  TRIP SEARCH (for riders) — POST /trips/search
// ─────────────────────────────────────────────────────────────

export interface TripSearchPayload {
  origin: string;        // e.g. "Ikeja City Mall"
  destination: string;   // e.g. "Jabi Lake Mall, Jabi"
  departureDate: string; // ISO date string e.g. "2024-12-25"
  passengers: number;    // minimum seats needed
}

/**
 * Searches available trips for riders.
 * Corresponds to: POST /trips/search
 * Requires auth token.
 */
export const searchTrips = async (
  payload: TripSearchPayload,
  token: string
): Promise<{ status: string; results: number; data: { trips: Trip[] } }> => {
  const response = await fetch(`${API_BASE_URL}/trips/search`, {
    method: "POST",
    headers: {
      "Content-Type": "application/json",
      Authorization: `Bearer ${token}`,
    },
    body: JSON.stringify(payload),
  });

  if (!response.ok) {
    const errData = await response
      .json()
      .catch(() => ({ message: "An unknown error occurred" }));
    throw new Error(
      errData.message || `Request failed with status ${response.status}`
    );
  }

  return response.json();
};


// ─────────────────────────────────────────────────────────────
//  BOOKING TYPES
// ─────────────────────────────────────────────────────────────

export type BookingStatus = "pending" | "confirmed" | "cancelled" | "completed";
export type PaymentStatus = "pending" | "paid" | "failed" | "refunded";

// Driver shape as populated inside a booking's trip
export interface BookingDriver {
  _id: string;
  personalInfo: {
    firstName: string;
    lastName: string;
    phoneNumber: string;
  };
  vehicleInfo: {
    make: string;
    model: string;
    year: string;
    color: string;
    plateNumber: string;
    passengerSeats: number;
    vin: string;
    photos: Array<{
      label: string;
      file: {
        fileName: string;
        fileSize: string;
        url: string;
      };
      _id: string;
    }>;
    documents: {
      registrationCertificate: { fileName: string; fileSize: string; url: string };
      insuranceCertificate: { fileName: string; fileSize: string; url: string };
      roadWorthiness: { fileName: string; fileSize: string; url: string };
    };
  };
}

// Trip shape as populated inside a booking
export interface BookingTrip {
  _id: string;
  id: string;
  driver: BookingDriver;           // fully populated — not just an ID string
  vehicle: TripVehicle;
  origin: TripLocation;
  destination: TripLocation;
  stops: TripLocation[];
  departureTime: string;
  pricePerSeat: number;
  totalSeats: number;
  availableSeats: number;
  status: TripStatus;
  description?: string;
  preferences: TripPreferences;
  bookings: string[];
  createdAt: string;
  updatedAt: string;
}

// Full booking shape — matches GET /trips/booked-trips response
export interface Booking {
  _id: string;
  id: string;
  trip: BookingTrip;
  rider: string;
  seatsBooked: number;
  totalPrice: number;
  status: BookingStatus;
  paymentInfo: {
    paymentStatus: PaymentStatus;
  };
  createdAt: string;
  updatedAt: string;
}

// ─────────────────────────────────────────────────────────────
//  BOOKING ENDPOINTS
// ─────────────────────────────────────────────────────────────

/**
 * Fetches all trips booked by the logged-in rider.
 * Corresponds to: GET /trips/booked-trips
 * Requires auth token.
 */
export const getBookedTrips = async (
  token: string
): Promise<{ status: string; results: number; data: { bookings: Booking[] } }> => {
  const response = await fetch(`${API_BASE_URL}/trips/booked-trips`, {
    method: "GET",
    headers: {
      "Content-Type": "application/json",
      Authorization: `Bearer ${token}`,
    },
  });

  if (!response.ok) {
    const errData = await response
      .json()
      .catch(() => ({ message: "An unknown error occurred" }));
    throw new Error(
      errData.message || `Request failed with status ${response.status}`
    );
  }

  return response.json();
};

// ─────────────────────────────────────────────────────────────
//  BOOK A TRIP (for riders)
// ─────────────────────────────────────────────────────────────

export interface BookTripPayload {
  tripId: string;
  seats: number; // backend expects "seats" not "seatsBooked"
}

// Booking shape returned from POST /trips/:id/book
// Note: trip is a string ID here — NOT populated like GET /trips/booked-trips
export interface BookTripResponse {
  _id: string;
  id: string;
  trip: string;          // just the trip ID — not populated
  rider: string;
  seatsBooked: number;
  totalPrice: number;
  status: BookingStatus;
  paymentInfo: {
    paymentStatus: PaymentStatus;
  };
  createdAt: string;
  updatedAt: string;
}

/**
 * Books a trip for the logged-in rider.
 * Corresponds to: POST /trips/:id/book
 * Body: { seats: number }
 * Returns 201 with booking object — trip field is a string ID (not populated).
 * After booking, call getBookedTrips() to get the full populated booking.
 */
export const bookTrip = async (
  payload: BookTripPayload,
  token: string
): Promise<{ status: string; message: string; data: { booking: BookTripResponse } }> => {
  const response = await fetch(`${API_BASE_URL}/trips/${payload.tripId}/book`, {
    method: "POST",
    headers: {
      "Content-Type": "application/json",
      Authorization: `Bearer ${token}`,
    },
    body: JSON.stringify({ seats: payload.seats }), // ← "seats" not "seatsBooked"
  });

  if (!response.ok) {
    const errData = await response
      .json()
      .catch(() => ({ message: "An unknown error occurred" }));
    throw new Error(
      errData.message || `Request failed with status ${response.status}`
    );
  }

  return response.json();
};

////////////
// ─────────────────────────────────────────────────────────────
//  TRIP BOOKINGS (for drivers) — GET /trips/:id/bookings
// ─────────────────────────────────────────────────────────────

export interface TripBookingPassenger {
  bookingId: string;
  seatsBooked: number;
  totalPrice: number;
  status: BookingStatus;
  rider: {
    firstName: string;
    lastName: string;
    phoneNumber: string;
  };
}

/**
 * Fetches all bookings for a specific trip — driver only.
 * Corresponds to: GET /trips/:id/bookings
 * Returns passenger names, phones, seats, payment status.
 */
export const getTripBookings = async (
  tripId: string,
  token: string
): Promise<{ status: string; results: number; data: TripBookingPassenger[] }> => {
  const response = await fetch(`${API_BASE_URL}/trips/${tripId}/bookings`, {
    method: "GET",
    headers: {
      "Content-Type": "application/json",
      Authorization: `Bearer ${token}`,
    },
  });

  if (!response.ok) {
    const errData = await response
      .json()
      .catch(() => ({ message: "An unknown error occurred" }));
    throw new Error(
      errData.message || `Request failed with status ${response.status}`
    );
  }

  return response.json();
>>>>>>> Stashed changes
};