import { createSlice, PayloadAction } from "@reduxjs/toolkit";
import type { RootState } from "@/store";
// import type {
//   Trip,
//   TripLocation,
//   TripStopInput,
//   TripPreferences,
//   TripVehicle,
//   TripStatus,
//   LuggagePolicy,
//   CreateTripPayload,
// } from "@/lib/api";

// export type {
//   Trip,
//   TripLocation,
//   TripStopInput,
//   TripPreferences,
//   TripVehicle,
//   TripStatus,
//   LuggagePolicy,
//   CreateTripPayload,
// };
// ─── Types ────────────────────────────────────────────────────────────────────

export type TripStatus = "scheduled" | "active" | "completed" | "cancelled";
export type LuggagePolicy = "none" | "light" | "medium" | "heavy";

export interface TripLocation {
  address: string;
  city: string;
  state: string;
  coordinates: [number, number]; // [lng, lat] — auto-generated by backend
  _id?: string;
}

// Stop input for CREATE payload — coordinates optional, backend fills them
export interface TripStopInput {
  address: string;
  city: string;
  state: string;
  coordinates?: [number, number];
}

export interface TripPreferences {
  smokingAllowed: boolean;
  petsAllowed: boolean;
  luggagePolicy: LuggagePolicy;
  instantBooking: boolean;
}

// Vehicle shape returned inside trip from GET /trips/my-trips (populated)
export interface TripVehicle {
  make: string;
  model: string;
  year: string;
  color: string;
  plateNumber: string;
}

// Full Trip — matches GET /trips/my-trips response shape
export interface Trip {
  _id: string;
  id: string;
  driver: string; // driver _id string
  vehicle: TripVehicle | string; // populated object from /my-trips, string id from POST /trips
  origin: TripLocation;
  destination: TripLocation;
  stops: TripLocation[];
  departureTime: string; // ISO date string
  pricePerSeat: number;
  totalSeats: number;
  availableSeats: number;
  status: TripStatus;
  description?: string;
  preferences: TripPreferences;
  bookings: string[]; // booking _id strings
  createdAt: string;
  updatedAt: string;
}

// ─── Create Trip Payload — matches POST /trips body ───────────────────────────
// originAddress and destinationAddress are flat strings.
// The backend geocodes them into full TripLocation objects with coordinates.

export interface CreateTripPayload {
  originAddress: string; // e.g. "Ikeja City Mall, Lagos"
  destinationAddress: string; // e.g. "Jabi Lake Mall, Abuja"
  departureTime: string; // ISO date string
  pricePerSeat: number;
  totalSeats: number;
  stops?: TripStopInput[]; // optional — coordinates auto-generated
  preferences: TripPreferences;
  description?: string;
}

// ─── State ────────────────────────────────────────────────────────────────────

interface TripState {
  currentTrip: Trip | null;
  tripHistory: Trip[];
  selectedTrip: Trip | null;
  isLoading: boolean;
  error: string | null;
}

const initialState: TripState = {
  currentTrip: null,
  tripHistory: [],
  selectedTrip: null,
  isLoading: false,
  error: null,
};

// ─── Slice ────────────────────────────────────────────────────────────────────

const tripSlice = createSlice({
  name: "trip",
  initialState,
  reducers: {
    // Called after POST /trips succeeds
    setCurrentTrip: (state, action: PayloadAction<Trip>) => {
      state.currentTrip = action.payload;
      state.error = null;
    },

    // Partial update — e.g. status change via socket
    updateCurrentTrip: (state, action: PayloadAction<Partial<Trip>>) => {
      if (state.currentTrip) {
        state.currentTrip = { ...state.currentTrip, ...action.payload };
      }
    },

    clearCurrentTrip: (state) => {
      state.currentTrip = null;
    },

    // Load all trips from GET /trips/my-trips
    setTripHistory: (state, action: PayloadAction<Trip[]>) => {
      state.tripHistory = action.payload;
    },

    // Prepend a newly created trip to history
    appendTrip: (state, action: PayloadAction<Trip>) => {
      state.tripHistory.unshift(action.payload);
    },

    // Set trip being viewed in detail (modal or detail page)
    setSelectedTrip: (state, action: PayloadAction<Trip | null>) => {
      state.selectedTrip = action.payload;
    },

    setTripLoading: (state, action: PayloadAction<boolean>) => {
      state.isLoading = action.payload;
    },

    setTripError: (state, action: PayloadAction<string | null>) => {
      state.error = action.payload;
    },

    // Full reset — call on logout alongside resetAuthState
    resetTripState: () => initialState,
  },
});

export const {
  setCurrentTrip,
  updateCurrentTrip,
  clearCurrentTrip,
  setTripHistory,
  appendTrip,
  setSelectedTrip,
  setTripLoading,
  setTripError,
  resetTripState,
} = tripSlice.actions;

// ─── Selectors ────────────────────────────────────────────────────────────────

export const selectCurrentTrip = (state: RootState) => state.trip.currentTrip;
export const selectTripHistory = (state: RootState) => state.trip.tripHistory;
export const selectSelectedTrip = (state: RootState) => state.trip.selectedTrip;
export const selectTripLoading = (state: RootState) => state.trip.isLoading;
export const selectTripError = (state: RootState) => state.trip.error;

// Derived selectors
export const selectScheduledTrips = (state: RootState) =>
  state.trip.tripHistory.filter((t) => t.status === "scheduled");

export const selectActiveTrips = (state: RootState) =>
  state.trip.tripHistory.filter((t) => t.status === "active");

export const selectCompletedTrips = (state: RootState) =>
  state.trip.tripHistory.filter((t) => t.status === "completed");

export const selectCancelledTrips = (state: RootState) =>
  state.trip.tripHistory.filter((t) => t.status === "cancelled");

export const selectTripById = (id: string) => (state: RootState) =>
  state.trip.tripHistory.find((t) => t._id === id || t.id === id) ?? null;

export const selectTripCount = (state: RootState) =>
  state.trip.tripHistory.length;

export default tripSlice.reducer;
